// <auto-generated />
using System;
using CobrarSeguros.BD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CobrarSeguros.BD.Migrations
{
    [DbContext(typeof(BDcontext))]
    [Migration("20220804135230_FechaCreacion")]
    partial class FechaCreacion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CobrarSeguros.BD.Data.entidades.Clientes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nroTelfonico")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("CobrarSeguros.BD.Data.entidades.Vehiculo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Patente")
                        .HasColumnType("int");

                    b.Property<int>("Sumasegurada")
                        .HasColumnType("int");

                    b.Property<string>("compañiaSeguro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nroPoliza")
                        .HasColumnType("int");

                    b.Property<string>("periodoPoliza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoSeguro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vigenciaPoliza")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
